version: '3.4'
services:
  alticci:
    image: alticci
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8080:8080"
    command: mvn spring-boot:run